### ISSUE TITLE
Held Items delivered remain on page user is redirected to

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#113]
Due to the async nature of `conveyor ! (hold, accept)`, when the user is returned to the `holdBrowse` page the item they have just resolved is still on the list.

Thoughts:
1. An easy win might be a Flash message explaining it will be removed once the process is complete
2. A more elegant solution may be to redirect to `holdBrowse` with a flag to exclude a specific `Item`. In this case, exclude the Item just released from displaying. This allows the async queue to do it's thing with less confusion to the user... but also would display the Item on the Hold screen in the future if indeed the Hold was unable to be resolved.

**Comment by richardrodgers** [comment]
Another approach would be to add a 'pending' state flag to the hold object in the DB (and set it when the async work started), and then we could show the whole list of holds, with an indication in the UI list.....

**Comment by JPrevost** [comment]
:+1:
