### ISSUE TITLE
Add Procfile for Heroku deployment

### ISSUE THREAD

**Issue by richardrodgers** [MITLibraries/scoap3hub#12]
Add ability to deploy to Heroku from Git. Intention is to maintain a usable public demo server on Heroku for non-developer use

**Comment by JPrevost** [comment]
This has some good information on how we might proceed with this. https://devcenter.heroku.com/articles/play-support

**Comment by richardrodgers** [comment]
Yea, the only deviation from that doc is we are hoping to trigger deploys from github, not from local git repo

**Comment by JPrevost** [comment]
Yup. Deploys are setup after the app is running on Heroku (or at least that's how I did it in my test project).

**Comment by JPrevost** [comment]
Want me to pull this ticket or do you have time to work on it Richard?

**Comment by richardrodgers** [comment]
Sure go ahead - but we should decide how we want to manage the Heroku account. We could, for now, use yours or mine, but I honestly don't know how to create a shared, institutional account. However, these actually can be decided later, since the ticket is just about config files. I mean it's sort of a separate issue

**Comment by JPrevost** [comment]
Heroku has the ability to transfer/share accounts in the admin. I'll set it up with mine and invite you as a co-owner. We can then deal with the permanent owner as we proceed.

**Comment by richardrodgers** [comment]
OK cool

**Comment by richardrodgers** [comment]
Procfile may be as simple as:


web: target/start -Dhttp.port=${PORT} ${JAVA_OPTS} -DapplyEvolutions.default=true

**Comment by JPrevost** [comment]
Thanks. I get the impression that heroku may automatically detect a play app and do that bit for us... but if not that'll be a great start as I really have no idea what I'm doing (in a good way).
