### ISSUE TITLE
Refactor app/views directory into a logical hierarchy

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#15]
I propose we create a hierarchy for `app/views`. I don't believe this would be much work to achieve and would probably make our lives easier as this project grows.

I'm thinking breaking it down in the same logical groupings that the `routes` use makes sense...or at least as a starting point. So maybe a directory structure something like:

```
app/views/home
app/views/publisher
app/views/collection
app/views/harvest
app/views/scheme
etc
```
We may also find it useful to rename the main template for each group to index.scala.html.

Let me know if I'm getting to Rails-y for you :)

**Comment by richardrodgers** [comment]
Not too Rails-y at all. I think it's a good idea to impose some structure in the views; you are right that they will become unwieldy soon enough (my preference is directories where shell tab name completion is a few characters).  Only question is whether to attack incrementally or systematically. I would say (and this bears on your pending pull req) that we might consider 'app/views/tags' as a place for functions used in multiple pages (like your _author thingy) - that's the conventional name.

**Comment by JPrevost** [comment]
Cool. I'd like to give this a go then as it'll make me learn a bit more about the controller/view relationship.

I'll hack at it in the morning then open a PR to allow us to discuss any specific hierarchy that isn't easy to decide on based on route or model naming.

**Comment by JPrevost** [comment]
@richardrodgers: A draft of this work can be seen here:
https://github.com/MITLibraries/scoap3hub/compare/author_display_limits...15_view_hierarchy

That link compares against the author_display_limits branch as I branched from it for an easier merge later. If that branch requires changes or we merge it I'll rebase this 15_view_hierarchy branch.

It may be easier to visualize the resultant changes here:
https://github.com/MITLibraries/scoap3hub/tree/15_view_hierarchy/app/views

It seems pretty good to me, but thoughts / suggestions are definitely welcome. I found myself wanting to rename some files too, but figured we should hammer this out first as the longer something like this stays open the harder work on other features will be to merge and this addresses the structural concern.

**Comment by JPrevost** [comment]
Per a 'hallway' conversation, we'll also make file renaming in scope for this ticket so I'll add additional commits to the branch to reflect what that might look like.

**Comment by JPrevost** [comment]
@richardrodgers I've updated the file names as well now with bd0b526 to remove the folder/file name duplication. Let me know if you have suggestions for specific or general changes.

FWIW, this is designed to slide in after #16 is merged.

**Comment by richardrodgers** [comment]
I'd say go ahead and merge it all - it's different enough that it'll be easier to react to the new structure than tinker with the old and a bunch a pending diffs....

**Comment by JPrevost** [comment]
Cool. I'll merge #16 then open a PR for this mess and then merge that if it still looks good... thanks.
