### ISSUE TITLE
Coverage was crashing Travis builds

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#162]
https://github.com/MITLibraries/scoap3hub/commit/831ac9cfdc5e844334d1fbf09c231e0f1a455c3c removes coverage testing in travis as it was crashing the builds.

It still works locally running this command in the project root:
`set clean coverage test`

However, it would be nice if it was debugged and re-enabled on Travis as that's a nice badge to be able to display on the repo for others that may consider using our project.

**Comment by richardrodgers** [comment]
Interesting that it is only manifesting now  - there were many iterations in which it did not crash. Is it perhaps length-of-build related?

**Comment by JPrevost** [comment]
I think it may be. Also, one of the builds just crashed again so who knows. There are no reported outages on Travis ¯\_(ツ)_/¯

**Comment by JPrevost** [comment]
My current thoughts on keeping an eye on this are:
- update our dependencies (sbt 0.13.8 and scala 2.11.6 and anything else that's easy to update that may be involved in this bug)
- re-enable coverage
- open a pr and see what happens.

**Comment by richardrodgers** [comment]
No harm in trying, but given that the local case is OK with earlier scala/sbt etc versions, I'm not optimistic.
I fear it may be more in corners of the CI environment that we have less visibility into/control over

**Comment by JPrevost** [comment]
I agree fully.

**Comment by JPrevost** [comment]
We can reopen if the merged changes don't remain stable.
