### ISSUE TITLE
Subscribers need to support multiple Users

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#192]
At this time, the relationship is one to one.

We should probably move directly to many-to-many to allow for future needs in #46 while also addressing the current need which is to allow multiple Users to act on behalf of a single Subscriber.

User Story: As a User, I want to share the work of managing a Subscriber with another User.

**Comment by richardrodgers** [comment]
Agreed, if we create a simple join table subscriber_user (or hub_user_subscriber), etc, that should handle future use cases along with current need
