### ISSUE TITLE
Establish method to kick off harvests on a schedule

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#206]
Currently, we have a notion of schedule able harvests with no mechanism to check back in and run the harvest automatically.

One option would be to create a route that calls a method that can be called by whatever cron-like process we end up using to run any harvests that are due to run.

**Comment by JPrevost** [comment]
@richardrodgers thoughts on requiring all harvests having a frequency of 1? Here's why I prefer that:

If we require all Harvests to have a frequency of 1, then we can just fire a cron-like job once a day that runs all of the harvests and grabs yesterdays content (or whatever updated + 1 day is, but hopefully that means yesterday in production).

We could still allow sysadmins to use the existing form to override that for one-off harvests (for catch up or testing or whatever).

If we allow some Harvests to have freq > 1, that means we need to build in more complex logic to determine whether we should run them (specifically, something like... get all the harvests and run only the ones where the last run date + freq is < today). That's doable of course, it's just messier than I think most use cases are going to require. In other words, I'm making the assumption that most Harvests should run daily to retrieve the previous day's records so let's just make that a rule until such time as somebody gives us a real good reason to support another value.

**Comment by richardrodgers** [comment]
I completely agree that 1 is a sensible default/rule/practice, and that we'd need to see a good reason to deviate from that. I suspect that the notion we've got now (frequency as an integer) may need refinement as cases get more complex, but it strikes me as premature optimization to to get into that now (The sort of stuff I mean are. e.g. multiple harvests where we may want to stagger for performance, etc)

**Comment by JPrevost** [comment]
Cool. I'll update the Harvest creation form to not expose freq and default it to 1 behind the scenes but leave it around for potential future use.

Speaking of premature optimization: we could handle staggered jobs (as future work) by doing something like tweaking the cron-like to run once per hour and selecting just one harvest that has not yet run today... that would work to spread load at least until we had 24 harvests defined and then we'd need to tweak again :)  But as we'll just have one to start I'll leave that fun for later.

**Comment by JPrevost** [comment]
FYI: Heroku Scheduler has been configured to run this nightly via curl at 4:00am.
