### ISSUE TITLE
Harvest Error Handling

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#211]
This is a summary of a discussion we had. Feel free to update with new information or to correct information I have wrong. I'm adding this as a ticket so we can link other tickets to it (some already exist) and keep track of when this work is "done".

### Can’t launch harvest: see #212 
What do we do?: Rollback and Alert Sysadmins via email. Do not automatically retry for now.
Errors included in this set:
- server not found
- timeout
- oai-error (other than noRecordsMatch... see No Data Returned)

### No or Bad Data Returned. see #214 
What do we do?: Check that noRecordsMatch is returned as an error state. If so, no problem.
If noRecordsMatch is not the error state, rollback and alert sysadmins.

If we don't get XML or the XML is not OAI-PMH, abort the harvest.

### Succeed in Getting IDset
What do we do?: Treat Item creation as an atomic set (opened continue token as separate ticket) for now.

### Catalog All Items Successful
What do we do?: nothing to do
could verify, but for now we’ll do that passively

### Not all Cataloged Successfully (or none cataloged successfully)
What do we do?: This should block from continuing to Indexer and Conveyor for this item
Errors included in this set:
- resource retrieval failed
- timeout
- host not found
- parse error
 - i.e. not valid xml?
- bad finder
 - some finders are required. If not found, this is an error state (ex. title)
- DB Error
 - any db error at this stage is an error state

### Other Notes
We discussed having a Failed Queue in the Cataloger worker, but at this time we’ll just use a passive web interface to allow SysAdmins to view the problem records.

We also discussed whether having the Cataloger call the Indexer and Conveyor directly instead of having a master Worker that controls flow would be best. For now we will leave as is. We don’t want to have the Harvester become a master controller as there are flows in which we anticipate have the ability to jump straight to cataloging for an Item that failed in certain states.

**Comment by JPrevost** [comment]
I have a new concern to work into this. The current assumption is that an Item with no Topics is in an Error state... which is correct. However, I think it's possible to have an Item with some Topics that is still in an Error state. This could happen if we are using multiple source files for the metadata. I don't think that happens in our current implementation, but I think we may need to have the Cataloger or Harvester keep track of what's going on and "Complete" processing on an Item.

Example. An Item gets the Title from source1.xml but ORCID from source2.xml. source2.xml retrieval fails and the processing chain halts (I think?)...although we'll be adding rescues in here soon. The Item will be incompletely processed. I haven't checked, but it's possible the Item could be Indexed and Conveyed at this point (not good) or just stop processing (still not good). In summary, as we work through these error catching keep this one in mind as well.

**Comment by richardrodgers** [comment]
I thought the example you mentioned was already captured above: "Not all cataloged successfully:
... block from continuing..." etc Is this a new concern? I still am a little unclear what the goal is. "Keeping track" may be a flow control issue that would benefit from workflow flags in the model, or other stateful bookkeeping in calling code (which is where I *think* you are going), but may not. I don't see it following from that description directly. I completely agree we will need to add logic to prevent blindly moving forward, but that was not in question I think.

We should have a design chat about this, there's a lot more to say really on this subject. For example, I have thought that we might also want to consider the other side of the coin: having a 'forgiving'  model that allows for failure of certain (possibly not always available) resources to add topics and such.

**Comment by JPrevost** [comment]
My concern is that in our model we have assumed that failures are detected by sysadmins being able to browse a list of Items with no Topics. This new scenario is that an Item fails after getting at least one Topic successfully and thus becomes non-detectable but is still effectively in an Error state.

We can safely continue the work on Exception handling here though and address this after we have a chance to discuss our options in more depth. I think adding bookkeeping (either in the Item model or in the processing chain) will slide in cleanly with this work if we determine it is useful.

**Comment by richardrodgers** [comment]
Guess I'm still not clear. In the case you describe (some topics found, some failed), would it not be the case that the cataloger would *not* assign the any/null topic at the end (which it would *only* do if it completed cataloging successfully)? That is, could we not use the test already in place?

Hope I'm not being dense here, sorry

**Comment by JPrevost** [comment]
You are correct. The method currently looks for Items with zero topics though, not just specifically Items without Any/None. That could easily change though without explicitly tracking state so is probably a good minimum solution to this concern.

**Comment by richardrodgers** [comment]
OK - great. I might be able to add a new convenience method when I put in some related work (a method to extract only topics from a given scheme). That should come in soon

**Comment by JPrevost** [comment]
Makes sense. Excellent.

**Comment by JPrevost** [comment]
Closing as I think with the latest merge we've completed what we intend to on this ticket.
