### ISSUE TITLE
Improve appearance of HTML Forms

### ISSUE THREAD

**Issue by richardrodgers** [MITLibraries/scoap3hub#23]
(from comments on PR #21) - Many forms (including the 'feedback' form) could benefit from using the bootstrap helper too at minimum, and possibly custom helpers. Resolution of this issue should begin by identifying the worst looking forms, and examining fixes, which may be more broadly applicable

**Comment by JPrevost** [comment]
We may choose to handle this as separate ticket, but I wanted to make a note that many of the workbench forms need to display hints or documentation to explain the types of data they are expecting.

It may be best for me to work on this as it'll force me to actually figure out what they are expecting :)

Some of this is complicated by the fact that the configuration of the hub actually determines what type of data will actually work... so it may require some introspection of existing data to best provide examples of what works in certain fields. (or we can just make the forms work for our purposes now and deal with changes for future data sources if/when they diverge from the scoap3 work).

Definitely a separate ticket but I want to document on this parent Form ticket until we discuss what to break out into separate tickets to work on. This is probably a concrete question for UX: I think we should create flows that make more sense to the end-user and aren't tied 1:1 with our data model. EX. extracting the abstract requires updating 3 different forms and ideally would be handled on a single form that then updates all models as appropriate.
