### ISSUE TITLE
Configure DB snapshots and confirm restore works

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#237]

**Comment by JPrevost** [comment]
It looks like we are already getting nightly backups of the PG database with a one week retention.

That seems legit to me.

Confirming how a db restore works with Heroku will be a darn good idea though so I'll leave this ticket open until that is tested.

**Comment by JPrevost** [comment]
I've confirmed I can download one of the automated backups locally and restore to my local pg server using `pg_restore`. (well, technically I just used pgAdmin3 which uses pg_restore under the hood).

Before we launch though, it will be worthwhile to run a backup, destroy the heroku db and reload from the backup while documenting the process so we don't have to figure that process out on-the-fly once in production.

**Comment by richardrodgers** [comment]
Cool! Where are the backups kept on Heroku (or can I easily find them)?

Richard

**Comment by JPrevost** [comment]
Backups are most easily found here I think:
https://postgres.heroku.com/databases/enigmatic-falls-8044-heroku-postgresql-cobalt#snapshots

The download button didn't seem to work in Safari, but in Chrome it eventually downloaded.

The resultant downloaded file has no extension, but is indeed a pg_dump file that pg_restore can use. Tips on what flags may be useful (like skipping owner permissions stuff) are found here:
https://devcenter.heroku.com/articles/heroku-postgres-import-export#restore-to-local-database

**Comment by JPrevost** [comment]
Restore is quite easy as well.

From local directory linked to heroku remote:

`heroku pg:backups` will list all available backups. The first column is the backup ID.

To restore the latest one, just do:
`heroku pg:backups restore` (you will be prompted to confirm it is a destructive action by entering the app name)

To restore a specific one, do:
`heroku pg:backups restore backupID HEROKU_POSTGRESQL_COBALT_URL` and replace `backupID` with the ID of the backup you want to use.

Example:
`heroku pg:backups restore a063 HEROKU_POSTGRESQL_COBALT_URL`

You will be prompted for a confirmation that this is a destructive action by entering the app name and then the restore will begin.

It would probably be good practice to snapshot the database in advance of any restore :)
`heroku pg:backups capture`

If you do that, your "latest" will be your manual backup so you'll need to do a targeted restore of whichever ID you want.
