### ISSUE TITLE
Template Interests may not be matching as new Topics flow into the Hub

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#288]
If I create a new template Interest, it will successfully create Topics for review for any existing Topics at the time that template is created.

However, I don't believe it is matching for new content flowing into the Hub after the template Interest is first created.

I haven't fully confirmed whether this description is entirely accurate and will update this ticket with more information.

**Comment by richardrodgers** [comment]
Looking at the code, I agree that that 'hook' was not registered in the cataloging workflow, so description is accurate. The methods for comparing new topics with existing interests exist, they are just not invoked.
It might require a bit of thought, given that we are now trying to verify that cataloging has completed successfully: thus it would be a mistake to fire the check before them.

**Comment by JPrevost** [comment]
Ah, thanks for looking into this a bit. Maybe a nightly cron looking for matches would be a good direction?

**Comment by richardrodgers** [comment]
Maybe - or we might just build a list of topics during cataloging, then *after* we know we have succeeded in completely cataloging, iterating that list and calling 'Conveyer.newTopic(topic)' for each. I'm slightly troubled by that amount of mutable state during cataloging, but It's probably OK

**Comment by richardrodgers** [comment]
For an (untested) example - look at 288_branch

**Comment by richardrodgers** [comment]
Sorry, should have made it a PR - but as it was untested I was cautious. All the changes are in the Cataloger worker - who keeps track of new topics - a few lines of code.

**Comment by JPrevost** [comment]
No worries, I'll test it out and open a PR/merge if I don't run into problems. Thanks!

**Comment by JPrevost** [comment]
Hmmm. The 288 branch doesn't have any commits that aren't in master. This can wait until you are back though since you've got the code to fix it.
