### ISSUE TITLE
Bonsai not working as expected

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#51]
I've tried this locally and via Heroku (and with different bonsai targets locally).

I can index items into a bonsai index manually via `curl` but via our app it doesn't work.

My best guess so far is that the URL is https or the fact we're passing a username/password in with the URL and play might not like that.

There's are sections of the docs that may be of use to track down either possibility, but before I did that I figured I'd open this Issue and see if @richardrodgers had any thoughts on this.

**Comment by richardrodgers** [comment]
Hmm, I could index items via the app (on the version of code before we added the BONSAI_URL config stuff) into a local instance of Elastic Search - not sure if that's what you mean by bonsai index, or do you mean curling to the Heroku Bonsai service?

**Comment by JPrevost** [comment]
The Cloud Bonsai service doesn't work. I've tracked it down to needing to use BasicAuth for WS and passing the username/password separately from the URL. (Seems a limitation in the WS implementation in the Play framework, but whatever).

It'll probably make more sense when I open a PR.

**Comment by JPrevost** [comment]
To be clear, the cloud service doesn't work with our app at present... it works from curl just fine.

**Comment by richardrodgers** [comment]
Hey Jeremy: thanks for this. Might it be less error-prone if we extract the username/password from the hub.index.url value string itself? - having separate config properties allows everything to diverge.
Pseudocody:

if (url has bonsai.io)
val split1 = url.indexOf(":")
val split2 = url.indexOf("@")
  WS.url(indexSvc.concat("item/").concat(item.id.toString))
+        .withAuth(url.substring("https://", split1), url.substring(split1, split2), WSAuthScheme.BASIC).put(stringify(toJson(dataMap)))

**Comment by JPrevost** [comment]
I considered something like that and couldn't decide which was better to be honest. If you somewhat prefer extracting from the single ENV to avoid missing a change on one in the future (which will happen) that's enough to push me in that direction though and I'll add a commit so we can see how that feels implemented.

The reason I waffle a bit on this is that I sort of think the single BonsaiURL with embedded username/password that heroku provides is a bit hacky to begin with.

**Comment by richardrodgers** [comment]
I agree it is a bit hacky - but the alternative is a bit prickly, in that one has to copy/paste URL fragments around, so I guess I have a slight preference for single VAR

**Comment by JPrevost** [comment]
Sounds good.
