### ISSUE TITLE
Configure remaining collections for SCOAP3

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#59]

**Comment by JPrevost** [comment]
http://repo.scoap3.org/oai2d?verb=ListSets

**Comment by JPrevost** [comment]
@richardrodgers I don't see any corresponding Journal in the public scoap3 repo for `PR_China` which appears on the ListSets? Thoughts? I'm guessing we ignore it for now...

**Comment by richardrodgers** [comment]
I guess so - just for yucks you might try to see if any records show up for that set in OAI-PMH:
ListLidentifiers&set=PR_China

**Comment by JPrevost** [comment]
Hmmm. It almost seems like either a subset or superset of some other collections... but I'm really not sure. It also shows up sometimes with the space and sometimes with `_` for extra fun.

http://repo.scoap3.org/oai2d?verb=ListIdentifiers&metadataPrefix=oai_dc&set=PR_China
