### ISSUE TITLE
Collection Policy

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#68]
There is a field for `policy` for a collection in which there is mostly placeholder information now. I have a question as to whether that should essentially be this phrase grabbed from the footer of every SCOAP3 page `Articles in the SCOAP3 repository are released under a CC-BY license. Metadata are provided by the corresponding publishers and released under the CC0 waiver.` or the statement found in the `540$a` field of the marcxml (a spot check shows it may be consistent).

Here's the question: are we trying to track the license for an article/item, or the metadata associated with it? If it's just the metadata, I'd go with the standard scoap3 phrase... if it's the article/item, the license should probably be extracted as metadata from each item and not applied at the collection level as it's likely to change over time (`CC-BY-3.0` to `CC-BY-4.0` etc)

**Comment by richardrodgers** [comment]
The policy field was a holdover from another use-case, and it kind of drops out in the SCOAP3 world, where a big part of what the project is about is securing a uniform (and open) access policy regardless of article origin. The policy field is displayed in the SWORD service document, but that's only when a hub is accepting SWORD deposits (we are not, just harvesting). I like the idea of the language taken from the footer, and I agree it's not item-specific, which should, as you say, be extracted from each item

**Comment by JPrevost** [comment]
Thanks!
