### ISSUE TITLE
Provide mechanism to know when a harvest is complete

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#69]
Currently there is no way in the UI to know when a harvest is running or complete.

It would be useful to know this information, even if it was just an admin feature.

Tailing logs is useful in development, but even then it's not clear if the harvest completed successfully or just stopped for some reason.

**Comment by JPrevost** [comment]
Hmmm. This is more complicated than I thought due to the use of Akka (when I pulled the ticket I naively was going to just do a `println("Harvest Complete)` at the end of a non-existing loop. 

It seems we throw an Item at a Catalog actor and assume it does it's thing. As that's all async, I'm not sure how best to track how many items are left to process.

One idea:
- For every Item we throw at the Cataloger, store it's oid in a db table.
- As the catalog finishes, remove the oid from the db table.

Pros:
- we know if a harvest is running (and can expose in the UI)
- we can tell how many items are processing with a simple count (and expose in the UI)
- we can detect if something has been running for a long time and allow admins to take action (or even automate the action in some cases). If an oid has been in the processing table for more than an hour (or whatever), either retry it's harvest or alert someone.
- similar to the previous, during application restart we could check to see if there are items in the queue and start the harvest again.

Cons:
- __This is way more work than I think we agreed to for this Sprint and we should probably punt it to another Sprint__

As part of that we could consider switching from `fire-and-forget` with the `!` to the Future with the `?` if that makes sense.

**Comment by JPrevost** [comment]
After discussion, it was determined to add the notion of `State` to an `Item` in the database which will allow the `Harvester` to create `Item` records with a `State` such as "Needs Cataloging" and have the `Cataloger` update the `State` to "Cataloged" when it has completed.

This could be extended to allow the `Indexer` and/or `Conveyer` to update the `Item` record, but we feel the main concern is knowing if/when the `Cataloger` completes successfully (i.e. updates the `State` to "Cataloged").

**Comment by richardrodgers** [comment]
A further reflection on this. I had forgot that the cataloger always - as it's final step - assigns a mandatory topic to each item: meta:any or meta:null (meaning that the item has, or lacks other topics). This is effectively the Item state we are looking for, I think. - No DB changes needed

**Comment by JPrevost** [comment]
You are correct. I'll see if anything I've written for this is still useful if changed to use that instead of the new field (I think some convenience methods might be). I have a minor concern about this regarding intentionality vs side effect and potential for confusion in the future, but I'll think it through some more and let you know my thoughts on it.
